REM PROGRAM TO PRINT THE LARGER OF
REM TWO INPUT NUMBERS
REM READ THE TWO INPUT VALUES
IN FIRST
IN SECOND
REM DECIDE WHICH IS LARGER BY COMPUTING
REM THE DIFFERENCE
LD SECOND
SUB FIRST
REM IF THE DIFFERENCE IS >= 0
REM BRANCH TO PRINT SECOND
BGTR ELSE
BZ ELSE
REM THE FIRST IS LARGER
OUT FIRST
B FINISH
REM ELSE THE SECOND IS LARGER
ELSE: OUT SECOND
FINISH: STOP
FIRST: DC 0
SECOND: DC 0